/**
 * ----------------------------------------------------------
 * Edge Optimizer
 * Request Engine for Cloudflare Workers - Extension Imports
 *
 * Crafted by Nishi Labo | https://4649-24.com
 * ----------------------------------------------------------
 *
 * This file imports extension modules that register themselves
 * with the extension registry in request_engine_core.ts.
 *
 * During deployment, this file is regenerated by the workflow
 * to include/exclude extensions based on workflow_dispatch inputs.
 *
 * Matches Python: GitHub Actions cat-merge of extensions/_ext_*.py
 */

// Extension: Security (eo.security.*)
import "../../../../common/ts/extensions/_ext_security";
