# EO_XXXXX values are specified in docker-compose.yml

# Docker Official Image
ARG EO_DOCKER_POSTGRES_IMAGE=postgres
ARG EO_DOCKER_POSTGRES_IMAGE_TAG=alpine
FROM ${EO_DOCKER_POSTGRES_IMAGE}:${EO_DOCKER_POSTGRES_IMAGE_TAG}

# Add customizations here if needed
# Example: Install additional packages, copy configuration files, etc.
# RUN apt-get update && apt-get install -y <package-name> && rm -rf /var/lib/apt/lists/*

