import pandas as pd
import os
import logging
import datetime

logger = logging.getLogger(__name__)

class Reporter:
    def __init__(self, results, config):
        self.results = results
        self.config = config
        self.output_dir = config["settings"].get("output_dir", "./reports")
        
    def generate_report(self):
        if not self.results:
            logger.warning("No results to report.")
            return

        os.makedirs(self.output_dir, exist_ok=True)
        
        df = pd.DataFrame(self.results)
        
        # Filter successful queries for latency/TPS metrics
        df_success = df[df["success"] == True]
        
        if df_success.empty:
            logger.error("All requests failed. Cannot generate performance report.")
            logger.error("Error sample:\n" + df["error"].head().to_string())
            return

        # Aggregation logic
        summary = df_success.groupby('engine').agg(
            total_req=('engine', 'count'),
            avg_ttft_ms=('ttft_ms', 'mean'),
            p90_ttft_ms=('ttft_ms', lambda x: x.quantile(0.90)),
            avg_tps=('tps', 'mean'),
            p90_tps=('tps', lambda x: x.quantile(0.10)),  # Low TPS is bad, so p10 is the 90th percentile of 'slowness'
            avg_e2e_ms=('e2e_ms', 'mean'),
        ).reset_index()
        
        # Calculate error rates from the full dataframe
        error_counts = df.groupby('engine')['success'].apply(lambda x: (~x).sum()).reset_index(name='error_count')
        
        summary = pd.merge(summary, error_counts, on='engine')
        
        # Format columns
        summary['avg_ttft_ms'] = summary['avg_ttft_ms'].round(1)
        summary['p90_ttft_ms'] = summary['p90_ttft_ms'].round(1)
        summary['avg_tps'] = summary['avg_tps'].round(1)
        summary['avg_e2e_ms'] = summary['avg_e2e_ms'].round(1)

        # Generate output strings
        md_table = summary.to_markdown(index=False)
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        
        report_content = f"""# EdgeOptimizer LLM Bench Report

**Timestamp**: {timestamp}
**Concurrency**: {self.config['settings'].get('concurrency')}
**Prompts Evaluated**: {len(self.results) // sum([1 for e in self.config.get('endpoints', []) if e.get('enabled')])} per engine

## Performance Summary

{md_table}

---
*Generated by EdgeOptimizer Local LLM Probe*
"""
        
        print("\n" + "="*50)
        print(report_content)
        print("="*50 + "\n")

        # Save to file
        report_file = os.path.join(self.output_dir, f"report_{timestamp}.md")
        with open(report_file, 'w', encoding='utf-8') as f:
            f.write(report_content)
            
        csv_file = os.path.join(self.output_dir, f"raw_data_{timestamp}.csv")
        df.to_csv(csv_file, index=False)
        
        logger.info(f"Report saved to {report_file}")
        logger.info(f"Raw data saved to {csv_file}")
