# EO_XXXXX values are specified in docker-compose.yml

# Docker Official Image
ARG EO_DOCKER_SEARXNG_IMAGE=docker.io/searxng/searxng
ARG EO_DOCKER_SEARXNG_IMAGE_TAG=latest
FROM ${EO_DOCKER_SEARXNG_IMAGE}:${EO_DOCKER_SEARXNG_IMAGE_TAG}

# Add customizations here if needed
# Example: Install additional packages, copy configuration files, etc.
# RUN apk add --no-cache <package-name>

