# EO_XXXXX values are specified in docker-compose.yml

# Docker Official Image
ARG EO_DOCKER_REDIS_IMAGE=redis
ARG EO_DOCKER_REDIS_IMAGE_TAG=alpine
FROM ${EO_DOCKER_REDIS_IMAGE}:${EO_DOCKER_REDIS_IMAGE_TAG}

# Add customizations here if needed
# Example: Install additional packages, copy configuration files, etc.
# RUN apk add --no-cache <package-name>

